# Generated by Django 5.0.3 on 2024-10-15 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashbord", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notes",
            old_name="tilte",
            new_name="title",
        ),
    ]
